services:
  - type: web
    name: hirepro-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: NDyuFEyzHYHZxwGelhLhVJrnMBLtcKfr
      - key: POSTGRES_DB
        value: railway
      - key: PGHOST
        value: ${{RAILWAY_PRIVATE_DOMAIN}}
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        value: ${{POSTGRES_DB}}
      - key: PGPASSWORD
        value: ${{POSTGRES_PASSWORD}}
      - key: PGUSER
        value: ${{POSTGRES_USER}}
      - key: DATABASE_URL
        value: postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}
      - key: DATABASE_PUBLIC_URL
        value: postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}
      - key: SSL_CERT_DAYS
        value: "820"
      - key: RAILWAY_DEPLOYMENT_DRAINING_SECONDS
        value: "60"
      - key: PGDATA
        value: "/var/lib/postgresql/data/pgdata"

  - type: cron
    name: hirepro-scraper
    env: python
    schedule: "0 */6 * * *"  # Run every 6 hours
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python scraper.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: NDyuFEyzHYHZxwGelhLhVJrnMBLtcKfr
      - key: POSTGRES_DB
        value: railway
      - key: PGHOST
        value: ${{RAILWAY_PRIVATE_DOMAIN}}
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        value: ${{POSTGRES_DB}}
      - key: PGPASSWORD
        value: ${{POSTGRES_PASSWORD}}
      - key: PGUSER
        value: ${{POSTGRES_USER}}
      - key: DATABASE_URL
        value: postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}
      - key: DATABASE_PUBLIC_URL
        value: postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}
      - key: SSL_CERT_DAYS
        value: "820"
      - key: RAILWAY_DEPLOYMENT_DRAINING_SECONDS
        value: "60"
      - key: PGDATA
        value: "/var/lib/postgresql/data/pgdata" 